### ISSUE TITLE
Publish release?

### ISSUE THREAD

**Issue by wezm** [mookid/diffr#1]
diffr looks like a handy tool. I'd love to create and [AUR](https://aur.archlinux.org/) package for it. It's best to build these against published releases instead of straight from git master though. I would be great if you could tag a [release](https://help.github.com/en/articles/creating-releases).

**Comment by mookid** [comment]
Thanks for the suggestion! 

Let me know if you make any progress. Because I am not familiar at all with AUR, please let me know the installation procedure so that I can update the README accordingly.

**Comment by mookid** [comment]
Great! thanks for the help!
