### ISSUE TITLE
Feature req: Italics style support

### ISSUE THREAD

**Issue by rpdelaney** [mookid/diffr#18]
Not all terminals support italics, but the one I use does! I think it could make some intuitive styles for refined text.

**Comment by rpdelaney** [comment]
I can get this effect in my terminal with `tput sitm` and end with `tput ritm`.

There's also a dim effect with (appropriately) `tput dim`.

**Comment by mookid** [comment]
hi @rpdelaney ,

this is a feature request for [termcolor](https://github.com/BurntSushi/termcolor/issues/15).
If the feature request lands there, I will be happy to support a new attribute.

I may give it a try but don't hold your breath.

**Comment by rpdelaney** [comment]
Third time's a charm.

It does look like [crossterm](https://docs.rs/crossterm/0.9.5/crossterm/index.html) supports more of these offbeat styles.

Would there be any way to allow a user to define their own pass-through values? Something like (just brainstorming here):

```
diffr --colors removed:background:124 \
  --rawcolors refine-removed:background:"$(tput setaf 124)":foreground:"$(tput dim ; tput setaf 15)"
```

**Comment by rpdelaney** [comment]
Nah that won't work, the shell will evaluate it before passing it to diffr. Maybe env vars would be better?

```
DIFFR_REFINE_REMOVED_BG="$(tput setaf 124)"
DIFFR_REFINE_REMOVED_FG="$(tput dim ; tput setaf 15)"
```

**Comment by mookid** [comment]
> 
> 
> Nah that won't work, the shell will evaluate it before passing it to diffr. Maybe env vars would be better?
> 
> ```
> DIFFR_REFINE_REMOVED_BG="$(tput setaf 124)"
> DIFFR_REFINE_REMOVED_FG="$(tput dim ; tput setaf 15)"
> ```

I would really avoid such solutions for the following reasons:
+ I would like configuration of diffr to be minimal (only command line args, no environment variable or whatever)
+ I would prefer to have the same kind of feature set for all such tools.

So progress on this will pass by improvements in diffr's dependencies.

**Comment by rpdelaney** [comment]
Fair enough. Thank you for filing the PR upstream. I'll follow that and leave it to you when to close this issue. Thanks! This is a neat tool.

**Comment by rpdelaney** [comment]
Thank you for running this down so diligently! Love this tool :)

**Comment by mookid** [comment]
I plan another trick in my bag for arbitrary ANSI escape code; stay tuned ;)

**Comment by rpdelaney** [comment]
Any chance there will be a release soon? I'm turning some of my colleagues on to using this with some styles I worked out for diffing terraform (since `terraform-fmt` constantly makes whitespace changes for alignment) but the releases in homebrew / AUR do not have all the features in the tip.

**Comment by mookid** [comment]
@rpdelaney done!

**Comment by rpdelaney** [comment]
https://github.com/Homebrew/homebrew-core/pull/51959
