### ISSUE TITLE
Leading +,- in diffs should receive common segment highlighting per GitHub

### ISSUE THREAD

**Issue by atweiden** [mookid/diffr#26]
Currently, in diffr's output, the leading `+` and `-` are highlighted with unique segment highlighting. This is not how GitHub diffs work, where the leading `+` and `-` receive common segment highlighting.

Relative to GitHub, diffr's current behavior is visually distracting. The leading `+` or `-` would be better off receiving common segment highlighting.

**Comment by mookid** [comment]
I am not sure to understand what you mean.

Do you mean that, for instance,
![image](https://user-images.githubusercontent.com/7757342/65249760-d2802680-daf4-11e9-9403-ae29e24a3c3a.png)


the refined highlighting starts at 'let app' rather than at column 0? if so, see #19

**Comment by atweiden** [comment]
![github-diffr-issue-26](https://user-images.githubusercontent.com/1638172/66381616-286e2d00-ea16-11e9-83eb-a783eeb25950.png)
