### ISSUE TITLE
[RFE] Use white as default color for letters

### ISSUE THREAD

**Issue by Hi-Angel** [mookid/diffr#31]
First of all, thanks for the better diff-highlight utility!

I was comparing `diffr` with the standard `diff-highlight` as provided by git, and although `diffr` gives better results, I noted its output somehow was less comfortable to look at. See:

git's `diff-highlight`:

![Screenshot_20190929_212204](https://user-images.githubusercontent.com/7935057/65837389-7fca1a00-e2ff-11e9-842d-fb433899dd32.png)

`diffr`:

![Screenshot_20190929_212516](https://user-images.githubusercontent.com/7935057/65837398-ab4d0480-e2ff-11e9-9370-8d8cd9779a0d.png)

I figured, the reason is that "black" color more likely to blend with the dark "green" and "red" than white color. The `diff-highlight` for that reason makes foreground letters white.

I think, it would make sense for `diffr` to also use by default a color that blends less with the background, for example "white".

**Comment by Hi-Angel** [comment]
Btw, worth noting that `diffr` screenshots in README has white-colored letters. Looks like something has changed since then.

**Comment by mookid** [comment]
@Hi-Angel can you please try to get the ANSI escape sequences for each screenshot?

**Comment by Hi-Angel** [comment]
Hmm… I'm trying to get them with `--color=always` to git, as in 

```
git log -1 -p cdec93b0bb4c8e59d59933c1c53cc2d99ff6c631 --color=always > /tmp/1
```

but for some reason the escape sequences around `.web_view` text are always missing…

**Comment by Hi-Angel** [comment]
Yay, I managed to do it! Here it is:

[diff-highlight-escape-output.txt](https://github.com/mookid/diffr/files/3668165/diff-highlight-escape-output.txt)
[diffr-escape-output.txt](https://github.com/mookid/diffr/files/3668166/diffr-escape-output.txt)

FTR: I obtained them as:
```bash
git log -1 -p cdec93b0bb4c8e59d59933c1c53cc2d99ff6c631 | /usr/share/git/diff-highlight/diff-highlight > /tmp/diff-highlight-escape-output.txt
git log -1 -p cdec93b0bb4c8e59d59933c1c53cc2d99ff6c631 | diffr > /tmp/diffr-escape-output.txt
```

**Comment by mookid** [comment]
Thanks for the report.
Note that on windows/cmd.exe, setting white makes no difference but degrades the output on osx/terminal (the white is a weird not-really-white foreground color).

What os/terminal emulator are you using? 

Note that a workaround to patching the default value in the code is to use the --colors option to set it: `--colors refine-added:foreground:white`

**Comment by Hi-Angel** [comment]
> Note that on windows/cmd.exe, setting white makes no difference but degrades the output on osx/terminal (the white is a weird not-really-white foreground color).

I looked at the escape outputs, as I see the `diff-highlight` doesn't actually set background nor foreground. It inverts colors instead, and the colors themselves apparently being added by git. I wonder if it makes sense to do the same for `diffr`, and if it would fix problems on all platforms?

> What os/terminal emulator are you using?

Archlinux/Konsole.

> Note that a workaround to patching the default value in the code is to use the --colors option to set it: `--colors refine-added:foreground:white`

Yeah, thanks, I mentioned  it in [my answer on stackoverflow](https://stackoverflow.com/a/58158446/2388257) too :)

**Comment by Hi-Angel** [comment]
> > Note that on windows/cmd.exe, setting white makes no difference but degrades the output on osx/terminal (the white is a weird not-really-white foreground color).
> 
> I looked at the escape outputs, as I see the `diff-highlight` doesn't actually set background nor foreground. It inverts colors instead, and the colors themselves apparently being added by git. I wonder if it makes sense to do the same for `diffr`, and if it would fix problems on all platforms?

Alternatively, I could add platform detection to my PR, so white would be the default everywhere except the OS X.

**Comment by mookid** [comment]
> Yeah, thanks, I mentioned it in [my answer on stackoverflow](https://stackoverflow.com/a/58158446/2388257) too :)

Thanks for the advertising!

> Alternatively, I could add platform detection to my PR, so white would be the default everywhere except the OS X.

Let's keep it simple and avoid that. Given that it seems to be a strict improvement in most cases, I think that your solution is the best one. Let's go with it at least for now.
