### ISSUE TITLE
Wrong-looking edge cases

### ISSUE THREAD

**Issue by s-mage** [mookid/diffr#33]
Hey!

First of all, you made a great tool, thank you.
I've brought you some examples where diffr works unexpected.

<img width="802" alt="Screenshot 2019-10-08 at 20 38 41" src="https://user-images.githubusercontent.com/2388396/66423270-a6790680-ea0b-11e9-98ee-3ffc55d5ab60.png">

[diffr-weirdness-left.txt](https://github.com/mookid/diffr/files/3704029/diffr-weirdness-left.txt)
[diffr-weirdness-right.txt](https://github.com/mookid/diffr/files/3704030/diffr-weirdness-right.txt)

So:

* it shouldn't highlight if there are only added or only removed changes
* `, :reward` and `:reward ,` is bouncing
* `campaign_path(object)` should be ignored altogether, and there is a redundant `)` highlighted

And sorry, I don't speak rust and can't help improving it

**Comment by mookid** [comment]
Hi @s-mage, thanks for the report!

> , :reward and :reward , is bouncing

There is little I can do about this. It may or may not improve in the future with changes in the algorithm.

> campaign_path(object) should be ignored altogether,

#27 should help with this one.

> and there is a redundant ) highlighted

I can't observe that on my machine. Can I get more info about your terminal setup?

**Comment by s-mage** [comment]
> Can I get more info about your terminal setup?

Sure, but what info do you need? It's iterm2 on macos, a font with ligatures (fira code)

**Comment by s-mage** [comment]
or maybe you use version from master, and I'm on 0.1.2

**Comment by mookid** [comment]
I will try to repro on my mac machine.

**Comment by mookid** [comment]
All are now fixed in the current version, closing.
