### ISSUE TITLE
Is there a way to compare 2 files on windows?

### ISSUE THREAD

**Issue by nico-abram** [mookid/diffr#4]
Ideally without requiring additional tools. I tried `fc file1 file2 | diffr` but it didn't work (I've heard fc is the equivalent of the diff command from linux). I'm on window 7 so I  can't ue WSL, and I'd rather not have to install cygwin just to compare 2 files.

**Comment by mookid** [comment]
This will not work because fc.exe does not seem to emit diff in unified format.

For a native port of diff, you can try
+ [diffutils from chocolatey](https://chocolatey.org/packages/diffutils)
+ if you have git installed, `git diff --no-index <file1> <file2>` works as well

**Comment by mookid** [comment]
By the way, I am interested to hear a report of diffr working on windows 7 (which it is supposed to, but I did not have the chance to test yet).

**Comment by nico-abram** [comment]
Seems to work fine with git. Sorry!
