### ISSUE TITLE
Show example of how to configure git to use diffr by default?

### ISSUE THREAD

**Issue by jedahan** [mookid/diffr#67]
I was able to use `GIT_PAGER=diffr` but then its not actually paging. Would be cool to see some examples of how to do this.

**Comment by waldyrious** [comment]
@jedahan are you perhaps looking for [this](https://github.com/mookid/diffr#integration-with-git)?

I prefer setting configs via the command line than by editing the gitconfig file, so here's how I did it in my experiments:

`git config --global core.pager 'diffr | less -R'`

or, to use something more elaborate:

`git config --global core.pager 'diffr --colors refine-removed:foreground:black:nobold --colors refine-added:foreground:black:nobold | less -RXF'`

I agree that having examples like these in the README would be helpful.

**Comment by waldyrious** [comment]
See also #41 and #62.

**Comment by jedahan** [comment]
I am blind; yes that works, thank you.
