### ISSUE TITLE
Question about highlighting trailing WS

### ISSUE THREAD

**Issue by figgis** [mookid/diffr#76]
Is there a a way to highlight trailing ws in git logs using diffr?
I have a few commits that failed on jenkins due to the fact that I've missed those since ws is indistinguishable from normal changes and doesn't stand out except that lines are a tad longer...

This is what i'm using today

```
[core]
	editor = '/usr/bin/nvim'
	pager = diffr --colors refine-added:none:background:0x33,0x99,0x33:bold --colors added:none:background:0x33,0x55,0x33 --colors refine-removed:none:background:0x99,0x33,0x33:bold --colors removed:none:background:0x55,0x33,0x33 | less -R
[interactive]
	difffilter = diffr --colors refine-added:none:background:0x33,0x99,0x33:bold --colors added:none:background:0x33,0x55,0x33 --colors refine-removed:none:background:0x99,0x33,0x33:bold --colors removed:none:background:0x55,0x33,0x33
```

**Comment by mookid** [comment]
this is the current output:

![image](https://user-images.githubusercontent.com/7757342/114627612-d0248500-9cb5-11eb-982c-e731f6d368dc.png)

What improvement do you expect?

**Comment by figgis** [comment]
Looks perfect! But I don't get that with with my settings. hat Am I missing?

**Comment by mookid** [comment]
this is not handled by diffr, the red background on whitespaces is emitted by git; it should be visible when you run git diff without diffr already.

if not, is https://stackoverflow.com/questions/5257553/coloring-white-space-in-git-diffs-output helpful?

**Comment by mookid** [comment]
closing for now, please feel free to reopen if needed.
