### ISSUE TITLE
Native Debian package

### ISSUE THREAD

**Issue by szubersk** [mookid/diffr#85]
@mookid I am working on a proposal to include `diffr` to the Debian packaging system.
The latest release happened on Mar 20, 2020 where `diffr` has a dependency on `diffr-lib`, an obstacle to the packaging as the dependency deserves a separate package.
Would you mind releasing version 1.5.0 containing #73, as well as other recent patches? I'll take care of packaging `diffr` and sending a proposal to Debian maintainers.

**Comment by mookid** [comment]
done! thanks for this effort. Please let me know if anything more is needed.

**Comment by szubersk** [comment]
Thank you, @mookid !
