### ISSUE TITLE
[Debian package] Missing man page

### ISSUE THREAD

**Issue by szubersk** [mookid/diffr#88]
Debian devs are positive about the upload and asked about providing a man page.

```
looks good so far. Would you maybe consider writing a manpage ? I know that's some effort but since upstream
doesn't have one yet that's a nice opportunity to contribute back.
```
https://salsa.debian.org/rust-team/debcargo-conf/-/merge_requests/485#note_393733

**Comment by mookid** [comment]
it would be nice to have one, for sure. could you give pointers as to how to make a simple man page from assets/help.txt ?

**Comment by szubersk** [comment]
@mookid please take a look at https://github.com/mookid/diffr/pull/89

**Comment by mookid** [comment]
awesome! thanks for the contribution!

**Comment by szubersk** [comment]
@mookid Would you mind releasing 1.6.0 to crates.io so we could use the man page in the official package?
