### ISSUE TITLE
Doesn't properly handle changed last line followed by "\ No newline at end of file"

### ISSUE THREAD

**Issue by ecm-pushbx** [mookid/diffr#90]
Running version 0.1.4 on an amd64 Debian host. The minus line (deleted) is treated as just deletion, all highlighted by diffr, and the `\ No newline at end of file` line and the following plus line (addition) are both not coloured at all.

**Comment by mookid** [comment]
hello @ecm-pushbx 
```
$ cat before <(echo @@@@@@) after <(echo @@@@@@)
abcd efgh ijkl@@@@@@
efgh ijkl mnop@@@@@@
```


![image](https://github.com/mookid/diffr/assets/7757342/19b2e8fc-e201-489d-8f05-ee8656450c95)

What would you expect to be different?

**Comment by ecm-pushbx** [comment]
It seems that my version is outdated, your test shows the wrong output on my end.

![Screenshot_20230806-180342](https://github.com/mookid/diffr/assets/31538682/00e8c2df-f405-4fee-8336-9465d0500d67)

I mentioned a version originally, but it probably helps more to list the commit ID, which was d20e32f. I tried to update the repo and rebuild the application. This revision seems to change the behaviour as desired: https://github.com/mookid/diffr/commit/d0ed0b92439d5a5bd86ec15a5783512ca6ea302f

**Comment by mookid** [comment]
cool! thanks for the bug report, and sorry for the slow response.
