### ISSUE TITLE
Highlighting of title of diffed file

### ISSUE THREAD

**Issue by zheneknew** [mookid/diffr#91]
Hey!
I see lines `diff --git ...`, `index ...`, `--- src/main.rs`, `+++src/main.rs` are highlighted in blue in your screenshot, and I very need it, but there are only `added|refine-added|removed|refine-removed` facenames in your docs.
Could you tell how did you highlight this section?
![image](https://github.com/mookid/diffr/assets/69075015/1778f8bb-823f-4ab5-9a8a-83ed3da1c3d1)

**Comment by mookid** [comment]
it's a git level config: I have
```
[color "diff"]
    meta = white blue

```
in my .gitconfig
